# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/student/Documents/HEPCAT_2025/INDAT-FPGA-lab/INDAT-FPGA-lab.srcs/sources_1/ip/xadc_wiz_0_1/xadc_wiz_0.xci
# IP: The module: 'xadc_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/student/Documents/HEPCAT_2025/INDAT-FPGA-lab/INDAT-FPGA-lab.gen/sources_1/ip/xadc_wiz_0_1/xadc_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/student/Documents/HEPCAT_2025/INDAT-FPGA-lab/INDAT-FPGA-lab.gen/sources_1/ip/xadc_wiz_0_1/xadc_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/student/Documents/HEPCAT_2025/INDAT-FPGA-lab/INDAT-FPGA-lab.srcs/sources_1/ip/xadc_wiz_0_1/xadc_wiz_0.xci
# IP: The module: 'xadc_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/student/Documents/HEPCAT_2025/INDAT-FPGA-lab/INDAT-FPGA-lab.gen/sources_1/ip/xadc_wiz_0_1/xadc_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/student/Documents/HEPCAT_2025/INDAT-FPGA-lab/INDAT-FPGA-lab.gen/sources_1/ip/xadc_wiz_0_1/xadc_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
